# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shrimp Data
email: shrimpdata@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Slogan here
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://shrimpdata.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: shrimpdata
github_username:  shrimpdata
#facebook_username: StartBootstrap

# Address information
#address_street: 3034 Melrose Place
#address_city: Beverly Hills
#address_state: CA
#address_zip: 90201

# Build settings
markdown: kramdown
